name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: ./build.sh
    - name: check
      run: ./faketime_ld 21137400 ./date
    - uses: actions/upload-artifact@v1
      with:
         name: faketime_ld
         path: faketime_ld
    - uses: actions/upload-artifact@v1
      with:
         name: date
         path: date
